# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 17:09
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import homes.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, help_text='Used for URLs, auto-generated from name if blank', max_length=250, populate_from='name', unique=True, verbose_name='Slug')),
                ('banner_image', sorl.thumbnail.fields.ImageField(upload_to=homes.models._generate_slider_image_file_name)),
                ('url_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Link')),
                ('publish_date', models.DateTimeField(verbose_name='Publish date')),
                ('ordering', models.IntegerField(blank=True, default=None, null=True, verbose_name='Ordering')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('open_in_new', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homes_bannerslider_created_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homes_bannerslider_modified_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banner Slider',
                'ordering': ['ordering'],
                'verbose_name_plural': 'Banner Sliders',
            },
        ),
    ]
