# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_cart', '0002_auto_20160408_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercart',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='date_merged',
        ),
    ]
