# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 05:23
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterNavigationMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('navigation', models.CharField(max_length=100, verbose_name='Navigation Menu')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, help_text='Used for URLs, auto-generated from name if blank', max_length=250, populate_from='navigation', unique=True, verbose_name='Slug')),
                ('link', models.CharField(blank=True, default=None, max_length=255, verbose_name='Url Link')),
                ('ordering', models.IntegerField(blank=True, default=None, null=True, verbose_name='Ordering')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('open_in_new', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigations_footernavigationmenu_created_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigations_footernavigationmenu_modified_user', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigations.FooterNavigationMenu')),
            ],
            options={
                'verbose_name': 'Navigation Footer Menu',
                'verbose_name_plural': 'Navigation Footer Menus',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('navigation', models.CharField(max_length=100, verbose_name='Navigation Menu')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, help_text='Used for URLs, auto-generated from name if blank', max_length=250, populate_from='navigation', unique=True, verbose_name='Slug')),
                ('link', models.CharField(blank=True, default=None, max_length=255, verbose_name='Url Link')),
                ('ordering', models.IntegerField(blank=True, default=None, null=True, verbose_name='Ordering')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigations_navigationmenu_created_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigations_navigationmenu_modified_user', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigations.NavigationMenu')),
            ],
            options={
                'verbose_name': 'Navigation Menu',
                'verbose_name_plural': 'Navigation Menus',
                'ordering': ['ordering'],
            },
        ),
    ]
