# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 03:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_uom', to='products.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 8, 3, 48, 52, 50430, tzinfo=utc), verbose_name='Publish date'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uom_uom', to='products.UOM'),
        ),
    ]
