# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 17:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20160313_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 13, 17, 25, 30, 675942, tzinfo=utc), verbose_name='Publish date'),
        ),
    ]
