# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 10:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20160321_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quick_overview',
            field=models.TextField(default='123', max_length=100, verbose_name='Quick Overview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='short_discription',
            field=models.TextField(default='123', max_length=100, verbose_name='Short Discription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 5, 10, 14, 1, 729964, tzinfo=utc), verbose_name='Publish date'),
        ),
    ]
