# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20160405_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 6, 16, 30, 34, 654930, tzinfo=utc), verbose_name='Publish date'),
        ),
    ]
