# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 16:08
from __future__ import unicode_literals

import autoslug.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20160408_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 8, 16, 8, 13, 222802, tzinfo=utc), verbose_name='Publish date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, help_text='Used for URLs, auto-generated from name if blank', max_length=250, populate_from='name', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='uom',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, help_text='Used for URLs, auto-generated from name if blank', max_length=250, populate_from='name', unique=True, verbose_name='Slug'),
        ),
    ]
