# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20160408_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 8, 17, 5, 25, 887486, tzinfo=utc), verbose_name='Publish date'),
        ),
    ]
