# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 14:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20160408_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AlterField(
            model_name='category',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 10, 14, 15, 52, 518858, tzinfo=utc), verbose_name='Publish date'),
        ),
    ]
