# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20160415_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 9, 40, 48, 31002, tzinfo=utc), verbose_name='Publish date'),
        ),
    ]
