# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20160420_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 20, 8, 30, 35, 424122, tzinfo=utc), verbose_name='Publish date'),
        ),
    ]
