# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 03:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20160420_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 26, 3, 56, 2, 563766, tzinfo=utc), verbose_name='Publish date'),
        ),
    ]
