# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 04:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20160426_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 26, 4, 24, 27, 942349, tzinfo=utc), verbose_name='Publish date'),
        ),
    ]
