# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 08:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20160426_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 27, 8, 2, 13, 245261, tzinfo=utc), verbose_name='Publish date'),
        ),
    ]
