# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 08:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20160427_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 27, 8, 34, 10, 17903, tzinfo=utc), verbose_name='Publish date'),
        ),
    ]
