# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_cart', '0003_auto_20160410_1415'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='uom',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='order_cart.OrderCart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Order DAte'),
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
