# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160426_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='order',
            name='line1',
            field=models.CharField(default='testing address', max_length=255, verbose_name='First line of address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='line2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Second line of address'),
        ),
        migrations.AddField(
            model_name='order',
            name='line3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Third line of address'),
        ),
        migrations.AddField(
            model_name='order',
            name='line4',
            field=models.CharField(blank=True, max_length=255, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(blank=True, max_length=64, verbose_name='Post/Zip-code'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=255, verbose_name='State/County'),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Miss', 'Miss'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr')], max_length=64, verbose_name='Title'),
        ),
    ]
